# Generated by Django 5.1.6 on 2025-02-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.CharField(default=str, max_length=100),
            preserve_default=False,
        ),
    ]
